### ISSUE TITLE
border Gradient

### ISSUE THREAD

**Issue by PiyushGoyal12** [PiyushGoyal12/Feyman_LandingPage#2]
Issue related to Hovering effect To solve in Sectionfour component present in Components folder of src folder
I want Border Gradient to be only visible if i hover on it but it is by default on gradient 
gradient is applied in span 107 line of sectionfour.scss
without hovering condition should be that border is of grey color
after hovering that gradient should be visible 
For Further Reference Contact me

here is a screen shot of without hovering i want when i hover it then only it should show like that else it should be grey
![issue 2](https://github.com/PiyushGoyal12/Feyman_LandingPage/assets/114993463/6c3ce416-c117-4bd9-8d96-f49e80c41cdb)

**Comment by imankush10** [comment]
File name and line no pls

**Comment by PiyushGoyal12** [comment]
> File name and line no pls

already mention Sectionfour and line no 107
